mil/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/jet/', admin.site.urls),
    path('military/', include('us.urls', namespace='military')),

]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

us/urls.py
from django.urls import path
from .views import (
    info_view,
    home_view,
    privacy_view,
    terms_view,
    section_view,
    fear_view,

)

app_name = 'us'
urlpatterns = [
    path('contact/', info_view, name='contact'),
    path('home/', home_view, name='home-view'),
    path('privacy/', privacy_view, name='privacy'),
    path('terms/', terms_view, name='terms'),
    path('section/', section_view, name='section'),
    path('no-fear/', fear_view, name='no-fear'),

]

us/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Information(models.Model):
    full_name = models.CharField(max_length=255)
    description = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True, null=False)
    email = models.EmailField(max_length=255)
    organization = models.CharField(max_length=255, default='U.S ARMY')
    reason = models.CharField(max_length=255, default='REGULAR')
    phone_number = models.CharField(max_length=255)
    requested = models.BooleanField(default=True)
    granted = models.BooleanField(default=False)

    def __str__(self):
        return self.email

class Reason(models.Model):
    why = models.CharField(max_length=225)

    def __str__(self):
        return f"{self.why}"

class Organization(models.Model):
    org = models.CharField(max_length=225)

    def __str__(self):
        return f"{self.org}"

us/forms.py
from django import forms
from .models import Organization, Reason, Information



class InfoForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 3,
        'placeholder': 'Comment * Max: 500 Characters',
        'class': 'form-control'
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'label':'name',
        'placeholder': 'email@',
        'class': 'form-control'}))
    full_name = forms.CharField(widget=forms.TextInput(attrs={
        'label': 'name',
        'placeholder': 'FULL NAME',
        'class': 'form-control'}))
    organization = forms.ModelChoiceField(widget=forms.Select(attrs={
        'class': 'form-control',
        'placeholder': 'select organization'
    }), queryset=Organization.objects.all(), to_field_name="org")
    reason = forms.ModelChoiceField(widget=forms.Select(attrs={
        'class': 'form-control',
        'placeholder': 'select your reason'
    }), queryset=Reason.objects.all(), to_field_name="why")
    phone_number = forms.CharField(widget=forms.NumberInput(attrs={
        'placeholder': 'your phone number',
        'class': 'form-control'
    }))

    class Meta:
        model = Information
        fields = ['full_name', 'email', 'description', 'reason', 'organization', 'phone_number']

us/views.py
from django.shortcuts import render
from .forms import InfoForm
from .models import Information


# Create your views here.
def info_view(request):
    form = InfoForm()
    if request.method == 'POST':
        form = InfoForm(request.POST or None)
        if form.is_valid():
            form.save()
        form = InfoForm()
    context = {
        'form': form,
    }
    return render(request, 'info.html', context)


def home_view(request):
    context = {

    }
    return render(request, 'home.html', context)


def privacy_view(request):
    context = {

    }
    return render(request, 'privacy.html', context)

def terms_view(request):
    context = {

    }
    return render(request, 'terms.html', context)

def section_view(request):
    context = {

    }
    return render(request, 'section.html', context)

def fear_view(request):
    context = {

    }
    return render(request, 'nofear.html', context)

templates/footer.html
{% extends 'base.html' %}
{% block content %}

{% load static %}

<footer>
    <section id="social-id" class="social">
        <ul>
            <li class="social-button facebook-button">
                <a rel="noopener noreferrer" target="_blank" href="#"><span>Official U.S. Army Facebook</span></a>
            </li>
            <li class="social-button twitter-button">
                <a rel="noopener noreferrer" target="_blank" href="#"><span>Official U.S. Army Twitter</span></a>
            </li>
            <li class="social-button youtube-button">
                <a rel="noopener noreferrer" target="_blank" href="#"><span>Official U.S. Army Youtube</span></a>
            </li>
            <li class="social-button flickr-button">
                <a rel="noopener noreferrer" target="_blank"
                   href="#"><span>Official U.S. Army Flickr</span></a>
            </li>
            <li class="social-button instagram-button">
                <a rel="noopener noreferrer" target="_blank" href="#"><span>Official U.S. Army Instagram</span></a>
            </li>
        </ul>
    </section>
    <section class="footer-bottom">
        <ul>
            <li><a href="{% url 'military:home-view' %}">Home</a></li>
            <li><a href="{% url 'military:contact' %}">Contact Us</a></li>
            <li><a href="{% url 'military:privacy' %}">Privacy</a></li>
            <li><a href="{% url 'military:terms' %}">Terms Of Use</a></li>
            <li><a href="http://dodcio.defense.gov/DoDSection508/Std_Stmt.aspx">Accessibility/Section 508</a></li>
            <li><a href="#">FOIA</a></li>
            <li><a href="{% url 'military:no-fear' %}">No FEAR Act</a></li>
        </ul>
    </section>
</footer>
{% endblock %}

templates/header.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<header>
    <div class="navbar">
        <div class="navbar-container">
            <a href="javascript:;" class="nav-button menu-button" aria-expanded="false" role="button">
                <span>MENU</span>
            </a>
            <a  class="nav-army-star">
                <span>HOME</span>
            </a>
            <a href="javascript:;" class="nav-button search-button" aria-expanded="false" role="button">
                <span>SEARCH</span>
            </a>
        </div>
    </div>
    <div class="nav-window menu-window">
        <div class="menu-container">
            <div class="list-container">
                <ul role="menu">
                    <li>
                        <input type="checkbox" id="menu-item-about"/>
                        <label for="menu-item-about" role="menuitem">ABOUT<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:home-view' %}">Who We Are</a></li>
                            <li><a href="{% url 'military:contact' %}">Organization</a></li>
                            <li><a href="{% url 'military:home-view' %}">Soldier and Family Resources</a></li>
                            <li><a href="{% url 'military:home-view' %}">Army A-Z</a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="menu-item-news"/>
                        <label for="menu-item-news" role="menuitem">NEWS<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:home-view' %}">Army Worldwide</a></li>
                            <li><a href="{% url 'military:home-view' %}">Press Releases</a></li>
                            <li><a href="{% url 'military:home-view' %}">Soldier Features</a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="menu-item-media"/>
                        <label for="menu-item-media" role="menuitem">MEDIA<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:home-view' %}">Photos</a></li>
                            <li><a href="{% url 'military:home-view' %}">Publications</a></li>
                        </ul>
                    </li>
                </ul>
                <ul role="menu">
                    <li>
                        <input type="checkbox" id="menu-item-leaders"/>
                        <label for="menu-item-leaders" role="menuitem">LEADERS<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:contact' %}">Secretary</a></li>
                            <li><a href="{% url 'military:contact' %}">Under Secretary</a></li>
                            <li><a href="{% url 'military:contact' %}">Chief of Staff</a></li>
                            <li><a href="{% url 'military:contact' %}">Vice Chief of Staff</a></li>
                            <li><a href="{% url 'military:contact' %}">Sergeant Major of the Army</a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="menu-item-features"/>
                        <label for="menu-item-features" role="menuitem">FEATURES<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:home-view' %}">Valor</a></li>
                            <li><a href="{% url 'military:home-view' %}">Events</a></li>
                            <li><a href="{% url 'military:home-view' %}">Heritage</a></li>
                            <li><a href="{% url 'military:section' %}">Army 101</a></li>
                        </ul>
                    </li>
                    <li class="social">
                        <ul>
                            <li class="social-button facebook-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army Facebook</span></a>
                            </li>
                            <li class="social-button twitter-button">
                                <a rel="noopener noreferrer" target="_blank" href="{% url 'military:home-view' %}"><span>Official U.S. Army Twitter</span></a>
                            </li>
                            <li class="social-button youtube-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army Youtube</span></a>
                            </li>
                            <li class="social-button instagram-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army Instagram</span></a>
                            </li>
                            <li class="social-button flickr-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army Flickr</span></a>
                            </li>
                            <li class="social-button linkedin-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army LinkedIn</span></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <ul class="quicklinks">
                <li><a href="{% url 'military:contact' %}">CONTACT US</a></li>
                <li><a href="{% url 'military:home-view' %}">Public Affairs</a></li>
                <li><a href="{% url 'military:terms' %}">SOCIAL MEDIA Guide</a></li>
                <li><a href="{% url 'military:home-view' %}">FAQs</a></li>
                <li><a href="{% url 'military:section' %}">AKO</a></li>
            </ul>
        </div>
    </div>
    <div class="nav-window search-window">
        <div class="search-form-container">
            <form accept-charset="UTF-8" action="{% url 'military:contact' %}" id="search_form" method="get">
                <div id="preload-01">
                    <input name="utf8" type="hidden" value="&#x2713;"/>
                    <input id="affiliate" name="affiliate" type="hidden" value="www.army.mil"/>
                </div>
                <label for="usagov-search-query">Search news, photos and videos on Army.mil</label>
                <input autocomplete="off" placeholder="Search" class="usagov-search-autocomplete"
                       id="usagov-search-query" name="query" type="text"/>
                <input aria-label="Search" name="commit" type="submit" value="" class="search-submit-button"/>
            </form>
        </div>
    </div>
</header>
<script src="{% static 'js/privacy_mini.js' %}"></script>

{% endblock %}

us/templates/privacy.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include "header.html" %}
<body>
<div class="main" role="main">
    <div class="page-banner parallax-image standard">
        <div class="full-width-image">
            <div class="overlay-effect"></div>
            <img style="background-image:url({% static 'images/milt/shadow.jpg' %}); ">
                 srcset="https://www.army.mil/e2/images/rv7/banners/privacy/2500.jpg 2500w, https://www.army.mil/e2/images/rv7/banners/privacy/1600.jpg 1600w, https://www.army.mil/e2/images/rv7/banners/privacy/768.jpg 768w"
                 alt="U.S. Army Privacy &amp; Security Policy" style="top: -60px;"></div>
        <div class="container">
            <div class="inner-container">
                <div class="left-container"><h1>Legal</h1>
                    <h2>Privacy &amp; Security Policy</h2></div>
            </div>
        </div>
    </div>
    <section class="gray-intro">
        <div class="container">
            <div class="inner-container"><p>Information available at <a href="{% url 'military:home-view' %}">www.army.mil</a> is
                consistent with Army and DoD policies and principles of information and contains information cleared for
                public release. Information intended for the internal Army audience is available through Army Knowledge
                Online (AKO) at <a href="{% url 'military:home-view' %}">www.us.army.mil.</a></p></div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="inner-container"><h4>Privacy Policy</h4>
                <p>This is an official U.S. Army website, and is provided as a public service by Army Public
                    Affairs.</p>
                <p>Information presented on Army.mil is considered public information and may be distributed or copied
                    unless otherwise specified. Use of appropriate byline/photo/image credits is requested.</p>
                <p>Privacy Act Statement - If you choose to provide us with personal information - like filling out a
                    Contact Us form with e-mail and/or postal addresses - we only use that information to respond to
                    your message or request. We will only share the information you give us with another government
                    agency if your inquiry relates to that agency, or as otherwise required by law. We never create
                    individual profiles or give it to any private organizations. Army.mil never collects information for
                    commercial marketing. While you must provide an e-mail address or postal address for a response
                    other than those generated automatically in response to questions or comments that you may submit,
                    we recommend that you NOT include any other personal information, especially Social Security
                    numbers. The Social Security Administration offers additional guidance on sharing your Social
                    Security number.</p>
                <p>For site management, information is collected for statistical purposes only. This government computer
                    system uses software programs to create summary statistics, which are used for such purposes as
                    assessing what information is of most and least interest, determining technical design
                    specifications, and identifying system performance or problem areas.</p>
                <p>For site security purposes and to ensure that this service remains available to all users, this
                    government computer system employs software programs to monitor network traffic to identify
                    unauthorized attempts to upload or change information, or otherwise cause damage.</p>
                <p>Except for authorized law enforcement investigations, no other attempts are made to identify
                    individual users or their usage habits. Raw data logs are used for no other purposes and are
                    scheduled for regular destruction in accordance with National Archives and Records Administration
                    guidelines.</p>
                <p>Unauthorized attempts to upload information or change information on this service are strictly
                    prohibited and may be punishable under the Computer Fraud and Abuse Act of 1986, Identity Theft
                    Enforcement and Restitution Act of 2008, and the National Information Infrastructure Protection
                    Act.</p><h4>Use of Measurement and Customization of Technology</h4>
                <p>When you visit a page on Army.mil, the internet browser on your computer may download a small file
                    (commonly called a "cookie") so that our website can recognize your computer when you use Army.mil
                    in the future. Army.mil uses first-party cookies to report on visitor interactions. These cookies
                    are used to store non-personally identifiable information. Browsers do not share first-party cookies
                    across domains. The U.S. Army does not use the information associated with cookies to track
                    individual user activity on the Internet outside Army websites, nor does it share the data obtained
                    through such technologies, without the user's explicit consent, with other departments or agencies.
                    The Department of the Army does not keep a database of information obtained from the use of
                    cookies.</p>
                <p>Cookies are enabled by default to optimize website functionality and customize user experience, but
                    users can choose not to accept the use of these cookies by changing the settings on their local
                    computer's web browser. The USA.gov website, <a href="{% url 'military:home-view'%}">usa.gov/optout-instructions</a>,
                    provides general instructions on how to opt out of cookies and other commonly used web measurement
                    and customization technologies. Opting out of cookies still permits users to access comparable
                    information and services; however, it may take longer to navigate or interact with the website if a
                    user is required to fill out certain information repeatedly.</p><h4>Specific
                    Technologies/Vendors</h4>
                <p>YouTube is utilized by this website for video delivery. For more details, please review <a
                        href="#">YouTube Terms of Service</a> and <a
                        href="{% url 'military:privacy' %}">Google Privacy Policy</a>. Akamai is utilized by this
                    website for content delivery. For more details, please review <a
                            href="{% url 'military:terms' %}">Akamai Terms &amp; Conditions</a>.
                    Google Analytics is utilized by this website. For more details, please review <a
                            href="{% url 'military:terms' %}">Google Analytics Terms
                        of Service</a>. The U.S. Army does not gather, request, record, require, collect or track any
                    internet users' personally identifiable information through these processes.</p>
                <p>Client side opt-out mechanisms allow the user to opt out of web measurement and customization
                    technologies by changing the settings of a specific application or program on the user's local
                    computer. For example, users may be able to disable persistent cookies by changing the settings on
                    commonly used web browsers. For general instructions on how to opt out of some of the most commonly
                    used web measurements and customization technologies, go to <a
                            href="{% url 'military:terms' %}">usa.gov/optout-instructions</a>.
                </p><h4>Use of Third-Party Websites and Applications</h4>
                <p>Third-party websites and applications that are not owned, operated, or controlled by the Department
                    of Defense are integral to Internet-based operations across the Department of Defense and used to
                    augment official communication. These capabilities include, but are not limited to, networking
                    services, media sharing services, wikis and data mashups. A list of the Defense Department's
                    authorized pages and uses of these services is listed at <a
                            href="{% url 'military:section' %}">defense.gov Resources Military-Departments/DOD-Websites</a>.
                    These sites may collect PII and may make it available to the Department of Defense and other users;
                    however, the PII is not collected on behalf of, nor is it provided specifically for, the Department
                    of Defense. The Department of Defense does not harvest and additionally collect, maintain, share or
                    otherwise use such PII for any purpose other than that for which it is made available to all users.
                </p>
                <p>If you have any questions or comments about the information presented here, please forward them to us
                    using our <a href="{% url 'military:contact' %}">Contact Us</a> page.</p></div>
        </div>
    </section>
</div>
{% include "footer.html" %}

<script>
    var usasearch_config={siteHandle:"www.army.mil"},script=document.createElement("script");script.type="text/javascript",script.src="https://search.usa.gov/javascripts/remote.loader.js",document.getElementsByTagName("head")[0].appendChild(script)
</script>
<script>
    !function(e,a,t,n,c,o,s){e.GoogleAnalyticsObject=c,e[c]=e[c]||function(){(e[c].q=e[c].q||[]).push(arguments)},e[c].l=1*new Date,o=a.createElement(t),s=a.getElementsByTagName(t)[0],o.async=1,o.src=n,s.parentNode.insertBefore(o,s)}(window,document,"script","//www.google-analytics.com/analytics.js","ga"),ga("create","UA-27189539-1","auto"),ga("send","pageview")
</script>
<div id="usasearch_sayt"
     style="background: none; border: 0px; display: block; float: none; height: 0px; line-height: 0; margin: 0px; padding: 0px; position: static; width: 0px;">
    <ul id="ui-id-1" tabindex="0" class="ui-menu ui-widget ui-widget-content ui-autocomplete ui-front"
        style="display: none;"></ul>
</div>
<div role="status" aria-live="assertive" aria-relevant="additions" class="ui-helper-hidden-accessible"></div>
</body>


{% endblock %}

us/templates/sss.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<header>
    <div class="navbar">
        <div class="navbar-container">
            <a href="javascript:;" class="nav-button menu-button" aria-expanded="false" role="button">
                <span>MENU</span>
            </a>
            <a  class="nav-army-star">
                <span>HOME</span>
            </a>
            <a href="javascript:;" class="nav-button search-button" aria-expanded="false" role="button">
                <span>SEARCH</span>
            </a>
        </div>
    </div>
    <div class="nav-window menu-window">
        <div class="menu-container">
            <div class="list-container">
                <ul role="menu">
                    <li>
                        <input type="checkbox" id="menu-item-about"/>
                        <label for="menu-item-about" role="menuitem">ABOUT<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:home-view' %}">Who We Are</a></li>
                            <li><a href="{% url 'military:contact' %}">Organization</a></li>
                            <li><a href="{% url 'military:home-view' %}">Soldier and Family Resources</a></li>
                            <li><a href="{% url 'military:home-view' %}">Army A-Z</a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="menu-item-news"/>
                        <label for="menu-item-news" role="menuitem">NEWS<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:home-view' %}">Army Worldwide</a></li>
                            <li><a href="{% url 'military:home-view' %}">Press Releases</a></li>
                            <li><a href="{% url 'military:home-view' %}">Soldier Features</a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="menu-item-media"/>
                        <label for="menu-item-media" role="menuitem">MEDIA<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:home-view' %}">Photos</a></li>
                            <li><a href="{% url 'military:home-view' %}">Publications</a></li>
                        </ul>
                    </li>
                </ul>
                <ul role="menu">
                    <li>
                        <input type="checkbox" id="menu-item-leaders"/>
                        <label for="menu-item-leaders" role="menuitem">LEADERS<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:contact' %}">Secretary</a></li>
                            <li><a href="{% url 'military:contact' %}">Under Secretary</a></li>
                            <li><a href="{% url 'military:contact' %}">Chief of Staff</a></li>
                            <li><a href="{% url 'military:contact' %}">Vice Chief of Staff</a></li>
                            <li><a href="{% url 'military:contact' %}">Sergeant Major of the Army</a></li>
                        </ul>
                    </li>
                    <li>
                        <input type="checkbox" id="menu-item-features"/>
                        <label for="menu-item-features" role="menuitem">FEATURES<span></span></label>
                        <ul>
                            <li><a href="{% url 'military:home-view' %}">Valor</a></li>
                            <li><a href="{% url 'military:home-view' %}">Events</a></li>
                            <li><a href="{% url 'military:home-view' %}">Heritage</a></li>
                            <li><a href="{% url 'military:section' %}">Army 101</a></li>
                        </ul>
                    </li>
                    <li class="social">
                        <ul>
                            <li class="social-button facebook-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army Facebook</span></a>
                            </li>
                            <li class="social-button twitter-button">
                                <a rel="noopener noreferrer" target="_blank" href="{% url 'military:home-view' %}"><span>Official U.S. Army Twitter</span></a>
                            </li>
                            <li class="social-button youtube-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army Youtube</span></a>
                            </li>
                            <li class="social-button instagram-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army Instagram</span></a>
                            </li>
                            <li class="social-button flickr-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army Flickr</span></a>
                            </li>
                            <li class="social-button linkedin-button">
                                <a rel="noopener noreferrer" target="_blank"
                                   href="{% url 'military:home-view' %}"><span>Official U.S. Army LinkedIn</span></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <ul class="quicklinks">
                <li><a href="{% url 'military:contact' %}">CONTACT US</a></li>
                <li><a href="{% url 'military:home-view' %}">Public Affairs</a></li>
                <li><a href="{% url 'military:terms' %}">SOCIAL MEDIA Guide</a></li>
                <li><a href="{% url 'military:home-view' %}">FAQs</a></li>
                <li><a href="{% url 'military:section' %}">AKO</a></li>
            </ul>
        </div>
    </div>
</header>
<script src="{% static 'js/privacy_mini.js' %}"></script>

{% endblock %}